---
name: "StackStorm Pack Workflow"

on:
  push:
    branches:
      - "trunk"
  pull_request:
    branches:
      - "trunk"

jobs:
  call_pack_workflow
    uses: "recursionpharma/github_workflows_rxrx_it/.github/workflows/stackstorm_pack.yml@trunk"
    secrets: "inherit"
